/** IPC invoke channels (renderer → main). */
export const IPC = {
  NAVIGATE: 'navigate',
  GO_HOME: 'go-home',
  GO_BACK: 'go-back',
  GO_FORWARD: 'go-forward',
  RELOAD: 'reload',
  STOP: 'stop',
  GET_BROWSER_STATE: 'get-browser-state',
  CREATE_TAB: 'create-tab',
  CREATE_PRIVATE_TAB: 'create-private-tab',
  CLOSE_TAB: 'close-tab',
  SWITCH_TAB: 'switch-tab',
  DUPLICATE_TAB: 'duplicate-tab',
  REOPEN_CLOSED_TAB: 'reopen-closed-tab',
  ZOOM_IN: 'zoom-in',
  ZOOM_OUT: 'zoom-out',
  ZOOM_RESET: 'zoom-reset',
  GET_ZOOM: 'get-zoom',
  FIND_IN_PAGE: 'find-in-page',
  FIND_NEXT: 'find-next',
  STOP_FIND_IN_PAGE: 'stop-find-in-page',
  TOGGLE_DEVTOOLS: 'toggle-devtools',
  GET_BOOKMARKS: 'get-bookmarks',
  ADD_BOOKMARK: 'add-bookmark',
  REMOVE_BOOKMARK: 'remove-bookmark',
  TOGGLE_BOOKMARK: 'toggle-bookmark',
  SET_CHROME_HEIGHT: 'set-chrome-height',
  SET_WEB_CONTENT_HIDDEN: 'set-web-content-hidden',
  SHOW_TOOLBAR_MENU: 'show-toolbar-menu',
  SHOW_PRIVACY_PANEL: 'show-privacy-panel',
  SHOW_SITE_PERMISSIONS: 'show-site-permissions',
  OPEN_EXTERNAL: 'open-external',
  SET_CONTENT_PROTECTION: 'set-content-protection',
  GET_CONTENT_PROTECTION: 'get-content-protection',
  GET_PRIVACY_STATE: 'get-privacy-state',
  UPDATE_PRIVACY_SETTINGS: 'update-privacy-settings',
  CLEAR_BROWSING_DATA: 'clear-browsing-data',
  WINDOW_MINIMIZE: 'window-minimize',
  WINDOW_TOGGLE_MAXIMIZE: 'window-toggle-maximize',
  WINDOW_CLOSE: 'window-close',
  WINDOW_IS_MAXIMIZED: 'window-is-maximized',
  CHROME_MENU_SELECT: 'chrome-menu-select',
  PRIVACY_PANEL_CLOSE: 'privacy-panel-close',
  PRIVACY_PANEL_UPDATE_SETTING: 'privacy-panel-update-setting',
  PRIVACY_PANEL_TOGGLE_PROTECTION: 'privacy-panel-toggle-protection',
  PRIVACY_PANEL_CLEAR_DATA: 'privacy-panel-clear-data',
  SITE_PERMISSIONS_CLOSE: 'site-permissions-close',
  SITE_PERMISSIONS_SET: 'site-permissions-set',
} as const;

/** IPC event channels (main → renderer). */
export const IPC_EVENTS = {
  BROWSER_STATE: 'browser-state',
  CONTENT_PROTECTION_STATE: 'content-protection-state',
  BOOKMARKS_UPDATED: 'bookmarks-updated',
  FIND_RESULT: 'find-result',
  PRIVACY_STATE: 'privacy-state',
  WINDOW_MAXIMIZED: 'window-maximized',
  CHROME_MENU_ACTION: 'chrome-menu-action',
  MENU_ITEMS: 'menu-items',
  PRIVACY_PANEL_DATA: 'privacy-panel-data',
  PRIVACY_PANEL_PROTECTION: 'privacy-panel-protection',
  SITE_PERMISSIONS_DATA: 'site-permissions-data',
} as const;
